[package]
name = "terminal_quizlit"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonschema = { version = "0.18.0", features = ["draft202012", "resolve-http", "resolve-file"] }
serde_json = "1.0.117"
